version: "3.8"
services:
  postgres: 
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=dat
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=cine-deep-match
    ports: 
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6739:6379" 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://dat:secret@postgres:5432/cine-deep-match?sslmode=disable
      - REDIS_SERVER_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]
