// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountEmailsByUserId(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error)
	CreateRecruiter(ctx context.Context, arg CreateRecruiterParams) (Recruiter, error)
	CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	GetEmailById(ctx context.Context, id uuid.UUID) (Email, error)
	GetEmailsByUserId(ctx context.Context, arg GetEmailsByUserIdParams) ([]Email, error)
	GetRecruiterById(ctx context.Context, id uuid.UUID) (Recruiter, error)
	GetRecruitersByUserId(ctx context.Context, userID uuid.UUID) ([]Recruiter, error)
	GetResume(ctx context.Context, userID uuid.UUID) (Resume, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (Email, error)
	UpdateRecruiterById(ctx context.Context, arg UpdateRecruiterByIdParams) (Recruiter, error)
	UpdateResume(ctx context.Context, arg UpdateResumeParams) (Resume, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
