// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: rpc_resume_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumePublicId string `protobuf:"bytes,3,opt,name=resume_public_id,json=resumePublicId,proto3" json:"resume_public_id,omitempty"`
	ResumeTitle    string `protobuf:"bytes,4,opt,name=resume_title,json=resumeTitle,proto3" json:"resume_title,omitempty"`
	ResumePdfUrl   string `protobuf:"bytes,5,opt,name=resume_pdf_url,json=resumePdfUrl,proto3" json:"resume_pdf_url,omitempty"`
}

func (x *Resume) Reset() {
	*x = Resume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resume_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resume_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_rpc_resume_service_proto_rawDescGZIP(), []int{0}
}

func (x *Resume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resume) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Resume) GetResumePublicId() string {
	if x != nil {
		return x.ResumePublicId
	}
	return ""
}

func (x *Resume) GetResumeTitle() string {
	if x != nil {
		return x.ResumeTitle
	}
	return ""
}

func (x *Resume) GetResumePdfUrl() string {
	if x != nil {
		return x.ResumePdfUrl
	}
	return ""
}

// Create Resume
type CreateResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumePublicId string `protobuf:"bytes,2,opt,name=resume_public_id,json=resumePublicId,proto3" json:"resume_public_id,omitempty"`
	ResumeTitle    string `protobuf:"bytes,3,opt,name=resume_title,json=resumeTitle,proto3" json:"resume_title,omitempty"`
	ResumePdfUrl   string `protobuf:"bytes,4,opt,name=resume_pdf_url,json=resumePdfUrl,proto3" json:"resume_pdf_url,omitempty"`
}

func (x *CreateResumeRequest) Reset() {
	*x = CreateResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resume_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeRequest) ProtoMessage() {}

func (x *CreateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resume_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeRequest.ProtoReflect.Descriptor instead.
func (*CreateResumeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resume_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResumeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateResumeRequest) GetResumePublicId() string {
	if x != nil {
		return x.ResumePublicId
	}
	return ""
}

func (x *CreateResumeRequest) GetResumeTitle() string {
	if x != nil {
		return x.ResumeTitle
	}
	return ""
}

func (x *CreateResumeRequest) GetResumePdfUrl() string {
	if x != nil {
		return x.ResumePdfUrl
	}
	return ""
}

type CreateResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
}

func (x *CreateResumeResponse) Reset() {
	*x = CreateResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resume_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeResponse) ProtoMessage() {}

func (x *CreateResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resume_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeResponse.ProtoReflect.Descriptor instead.
func (*CreateResumeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resume_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// Get Resume
type GetResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetResumeRequest) Reset() {
	*x = GetResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resume_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeRequest) ProtoMessage() {}

func (x *GetResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resume_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeRequest.ProtoReflect.Descriptor instead.
func (*GetResumeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resume_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetResumeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
}

func (x *GetResumeResponse) Reset() {
	*x = GetResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resume_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeResponse) ProtoMessage() {}

func (x *GetResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resume_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeResponse.ProtoReflect.Descriptor instead.
func (*GetResumeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resume_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

// Update Resume
type UpdateResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResumePublicId *string `protobuf:"bytes,2,opt,name=resume_public_id,json=resumePublicId,proto3,oneof" json:"resume_public_id,omitempty"`
	ResumeTitle    *string `protobuf:"bytes,3,opt,name=resume_title,json=resumeTitle,proto3,oneof" json:"resume_title,omitempty"`
	ResumePdfUrl   *string `protobuf:"bytes,4,opt,name=resume_pdf_url,json=resumePdfUrl,proto3,oneof" json:"resume_pdf_url,omitempty"`
}

func (x *UpdateResumeRequest) Reset() {
	*x = UpdateResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resume_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeRequest) ProtoMessage() {}

func (x *UpdateResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resume_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeRequest.ProtoReflect.Descriptor instead.
func (*UpdateResumeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resume_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResumeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateResumeRequest) GetResumePublicId() string {
	if x != nil && x.ResumePublicId != nil {
		return *x.ResumePublicId
	}
	return ""
}

func (x *UpdateResumeRequest) GetResumeTitle() string {
	if x != nil && x.ResumeTitle != nil {
		return *x.ResumeTitle
	}
	return ""
}

func (x *UpdateResumeRequest) GetResumePdfUrl() string {
	if x != nil && x.ResumePdfUrl != nil {
		return *x.ResumePdfUrl
	}
	return ""
}

type UpdateResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
}

func (x *UpdateResumeResponse) Reset() {
	*x = UpdateResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resume_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResumeResponse) ProtoMessage() {}

func (x *UpdateResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resume_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResumeResponse.ProtoReflect.Descriptor instead.
func (*UpdateResumeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resume_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

var File_rpc_resume_service_proto protoreflect.FileDescriptor

var file_rpc_resume_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa4,
	0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x24, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x64, 0x66, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x50,
	0x64, 0x66, 0x55, 0x72, 0x6c, 0x22, 0xa1, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x64,
	0x66, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x50, 0x64, 0x66, 0x55, 0x72, 0x6c, 0x22, 0x3a, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0xe9, 0x01, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x10,
	0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x64,
	0x66, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x64, 0x66, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x13,
	0x0a, 0x11, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x69, 0x64, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f,
	0x70, 0x64, 0x66, 0x5f, 0x75, 0x72, 0x6c, 0x22, 0x3a, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x44, 0x65, 0x65, 0x2d, 0x44, 0x65, 0x65, 0x2d, 0x54, 0x69, 0x67, 0x65, 0x72, 0x2d,
	0x48, 0x61, 0x63, 0x6b, 0x73, 0x2f, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_resume_service_proto_rawDescOnce sync.Once
	file_rpc_resume_service_proto_rawDescData = file_rpc_resume_service_proto_rawDesc
)

func file_rpc_resume_service_proto_rawDescGZIP() []byte {
	file_rpc_resume_service_proto_rawDescOnce.Do(func() {
		file_rpc_resume_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_resume_service_proto_rawDescData)
	})
	return file_rpc_resume_service_proto_rawDescData
}

var file_rpc_resume_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_resume_service_proto_goTypes = []interface{}{
	(*Resume)(nil),               // 0: pb.Resume
	(*CreateResumeRequest)(nil),  // 1: pb.CreateResumeRequest
	(*CreateResumeResponse)(nil), // 2: pb.CreateResumeResponse
	(*GetResumeRequest)(nil),     // 3: pb.GetResumeRequest
	(*GetResumeResponse)(nil),    // 4: pb.GetResumeResponse
	(*UpdateResumeRequest)(nil),  // 5: pb.UpdateResumeRequest
	(*UpdateResumeResponse)(nil), // 6: pb.UpdateResumeResponse
}
var file_rpc_resume_service_proto_depIdxs = []int32{
	0, // 0: pb.CreateResumeResponse.resume:type_name -> pb.Resume
	0, // 1: pb.GetResumeResponse.resume:type_name -> pb.Resume
	0, // 2: pb.UpdateResumeResponse.resume:type_name -> pb.Resume
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_resume_service_proto_init() }
func file_rpc_resume_service_proto_init() {
	if File_rpc_resume_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_resume_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resume_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resume_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resume_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resume_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resume_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resume_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_resume_service_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_resume_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_resume_service_proto_goTypes,
		DependencyIndexes: file_rpc_resume_service_proto_depIdxs,
		MessageInfos:      file_rpc_resume_service_proto_msgTypes,
	}.Build()
	File_rpc_resume_service_proto = out.File
	file_rpc_resume_service_proto_rawDesc = nil
	file_rpc_resume_service_proto_goTypes = nil
	file_rpc_resume_service_proto_depIdxs = nil
}
